-- MySQL Script generated by MySQL Workbench
-- Mon Nov  9 13:42:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cmeidb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cmeidb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cmeidb` DEFAULT CHARACTER SET utf8 ;
USE `cmeidb` ;

-- -----------------------------------------------------
-- Table `cmeidb`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmeidb`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmeidb`.`bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmeidb`.`bairro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bairro_cidade1_idx` (`cidade_id` ASC) ,
  CONSTRAINT `fk_bairro_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `cmeidb`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmeidb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmeidb`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `bairro_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_endereco_bairro1_idx` (`bairro_id` ASC) ,
  CONSTRAINT `fk_endereco_bairro1`
    FOREIGN KEY (`bairro_id`)
    REFERENCES `cmeidb`.`bairro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmeidb`.`cmei`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmeidb`.`cmei` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` INT(30) NOT NULL,
  `id_endereco` INT NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cmei_enderco1_idx` (`id_endereco` ASC) ,
  CONSTRAINT `fk_cmei_enderco1`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `cmeidb`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmeidb`.`crianca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmeidb`.`crianca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sexo` TINYINT NOT NULL,
  `nascimento` DATE NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `registro` INT(30) NOT NULL,
  `livro` VARCHAR(45) NULL,
  `folha` VARCHAR(45) NULL,
  `cpf` INT(30) NULL,
  `endereco_id` INT NOT NULL,
  `cmei_opcao1` INT NOT NULL,
  `cmei_opcao2` INT NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_crianca_enderco1_idx` (`endereco_id` ASC) ,
  INDEX `fk_crianca_cmei1_idx` (`cmei_opcao1` ASC) ,
  INDEX `fk_crianca_cmei2_idx` (`cmei_opcao2` ASC) ,
  CONSTRAINT `fk_crianca_enderco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `cmeidb`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crianca_cmei1`
    FOREIGN KEY (`cmei_opcao1`)
    REFERENCES `cmeidb`.`cmei` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crianca_cmei2`
    FOREIGN KEY (`cmei_opcao2`)
    REFERENCES `cmeidb`.`cmei` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmeidb`.`responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmeidb`.`responsavel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(160) NOT NULL,
  `cpf` INT(30) NOT NULL,
  `telefone_1` INT(60) NULL,
  `telefone_2` INT(60) NULL,
  `trabalho` VARCHAR(45) NULL,
  `renda` FLOAT NULL,
  `pensao` FLOAT NULL,
  `numero_titulo` INT(60) NULL,
  `zona_titulo` INT(60) NULL,
  `secao_titulo` INT(60) NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmeidb`.`aux_crianca_responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmeidb`.`aux_crianca_responsavel` (
  `responsavel_id` INT NOT NULL,
  `crianca_id` INT NOT NULL,
  `tipo` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`responsavel_id`, `crianca_id`),
  INDEX `fk_responsavel_has_crianca_crianca1_idx` (`crianca_id` ASC) ,
  INDEX `fk_responsavel_has_crianca_responsavel1_idx` (`responsavel_id` ASC) ,
  CONSTRAINT `fk_responsavel_has_crianca_responsavel1`
    FOREIGN KEY (`responsavel_id`)
    REFERENCES `cmeidb`.`responsavel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_responsavel_has_crianca_crianca1`
    FOREIGN KEY (`crianca_id`)
    REFERENCES `cmeidb`.`crianca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmeidb`.`criteriosocial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmeidb`.`criteriosocial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `peso` INT(12) NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmeidb`.`contemplado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmeidb`.`contemplado` (
  `crianca_id` INT NOT NULL,
  `data` DATE NOT NULL,
  `aceitou` TINYINT NOT NULL,
  `continua_lista` TINYINT NOT NULL,
  `id_cmei` INT NOT NULL,
  PRIMARY KEY (`crianca_id`),
  INDEX `fk_contemplado_cmei1_idx` (`id_cmei` ASC) ,
  INDEX `fk_contemplado_crianca1_idx` (`crianca_id` ASC) ,
  CONSTRAINT `fk_contemplado_cmei1`
    FOREIGN KEY (`id_cmei`)
    REFERENCES `cmeidb`.`cmei` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contemplado_crianca1`
    FOREIGN KEY (`crianca_id`)
    REFERENCES `cmeidb`.`crianca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cmeidb`.`aux_crianca_criterio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmeidb`.`aux_crianca_criterio` (
  `crianca_id` INT NOT NULL,
  `criteriosocial_id` INT NOT NULL,
  PRIMARY KEY (`crianca_id`, `criteriosocial_id`),
  INDEX `fk_crianca_has_criteriosocial_criteriosocial1_idx` (`criteriosocial_id` ASC) ,
  INDEX `fk_crianca_has_criteriosocial_crianca1_idx` (`crianca_id` ASC) ,
  CONSTRAINT `fk_crianca_has_criteriosocial_crianca1`
    FOREIGN KEY (`crianca_id`)
    REFERENCES `cmeidb`.`crianca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crianca_has_criteriosocial_criteriosocial1`
    FOREIGN KEY (`criteriosocial_id`)
    REFERENCES `cmeidb`.`criteriosocial` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
